export const FETCH_TIMER = 'FETCH_TIMER';
export const UPDATE_TIMER = 'UPDATE_TIMER';

export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const FETCH_SESSION = 'FETCH_SESSION';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';